### ISSUE TITLE
Bokeh streams callback fails with convert_timestamp in Python 2.7

### ISSUE THREAD

**Issue by darynwhite** [ioam/holoviews#3412]
Discovered this while writing a BoundsX to review dates of a selected data points in a time series. It fails out and kills the stream.

https://github.com/ioam/holoviews/blob/9a6a630b727c8827a8bd6fbe77bf31e1f35a7e5a/holoviews/plotting/bokeh/util.py#L89

The output from browser console:
```
Python failed with the following traceback:
~/conda/lib/python2.7/site-packages/pyviz_comms/__init__.py _handle_msg L296
~/conda/lib/python2.7/site-packages/holoviews/plotting/bokeh/callbacks.py on_msg L121
~/conda/lib/python2.7/site-packages/holoviews/plotting/bokeh/callbacks.py _process_msg L821
~/conda/lib/python2.7/site-packages/holoviews/plotting/bokeh/util.py convert_timestamp L89
	AttributeError: 'module' object has no attribute 'timezone'
```

**Comment by darynwhite** [comment]
Is this a bug or just an unfortunate result of writing for 3.6+ and trying to support 2.7.15?

**Comment by philippjfr** [comment]
Both I guess. Should have added unit tests which would have caught this, since all core developers now use 3.6+.

**Comment by darynwhite** [comment]
I'm working on moving our code library to be 3.6+ compatible, but it isn't as simple as a conversion script unfortunately. Some dependencies have to be replaced so identifying replacements has been difficult. Library runs fine in 2.7.15 so I have to rely on that while working on updates. Should I just edit my install as a work around for the time being?

**Comment by philippjfr** [comment]
Sure, a PR would also be appreciated if you work out a fix. That way we can try to get the fix into the 1.10.2 release scheduled for later this week or early next week.

**Comment by darynwhite** [comment]
What's the reasoning behind not using [`dt.datetime.utcfromtimestamp`](https://docs.python.org/2/library/datetime.html#datetime.datetime.utcfromtimestamp) or was this overlooked?

**Comment by philippjfr** [comment]
Sounds like that was simply overlooked.
